version: '3'

services:
  # Spark Master
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master port
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  # Spark Worker 1
  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  # Spark Worker 2
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sparkdb
    ports:
      - "5432:5432"  # PostgreSQL port
    volumes:
          - ../src/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data locally
    networks:
      - spark-network

  # Jupyter Notebook
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"  # Jupyter Notebook port
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - NB_USER=jovyan
    command: >
      bash -c "pip install psycopg2-binary sqlalchemy && start-notebook.sh --NotebookApp.token='' --ServerApp.allow_password_change=False"
    # command: >
    #   start-notebook.sh --NotebookApp.token='' --ServerApp.allow_password_change=False
    volumes:
      - ../src/notebook:/home/jovyan/work  # Host directory for saving notebooks
      - ../src/data:/home/jovyan/data
    depends_on:
      - spark-master
      - postgres
    networks:
      - spark-network

  # Flask API
  flask-api:
    build:
      context: ../src/flask_api  # Flask API directory
    container_name: flask-api
    ports:
      - "5000:5000"  # Expose Flask API on port 5000
    depends_on:
      - postgres  # Flask depends on PostgreSQL to be up
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
